=== turkishpropbank/turkishpropbank.github.io/frames/framesetTR.dtd
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>

<!ELEMENT predicate (note | roleset | infSuffixes)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>

<!ELEMENT roleset (note*, roles, ( example | note )*)>
<!ATTLIST roleset 
  id   ID #REQUIRED
  name CDATA #IMPLIED
  vncls CDATA #IMPLIED
  framnet CDATA #IMPLIED>
  
<!ELEMENT roles   (note | role)*>

<!ELEMENT role (vnrole*) >
<!ATTLIST role 
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  suffix CDATA #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #IMPLIED

  vntheta (Actor1 | Actor2| Agent| Asset| Attribute| Beneficiary| Cause|
  Destination| Experiencer| Extent| Instrument| Location| Material| Patient|
  Patient1| Patient2| Predicate| Product| Recipient| Source| Stimulus| Theme|
  Theme1| Theme2| Time| Topic) #IMPLIED>
       
<!ELEMENT infSuffix (infSuffix*)>	   
<!ATTLIST infSuffix 
  id CDATA #REQUIRED
  desc CDATA #IMPLIED>
  
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>

<!ELEMENT text (#PCDATA)>

<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">

<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  suffix CDATA #REQUIRED>
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== turkishpropbank/turkishpropbank.github.io/frames/kak.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="kak">


<roleset id="kak.01" name="İtmek, vurmak">
<roles>
<role descr="kakan" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="kakılan" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="patient"/>
</role>

<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Etiler'in renkli gece hayatında, onlarca kamera önünde sevgilisini dövdü, itip kaktı</text>


<note/>
<arg f="tmp" n="m" suffix="">Etiler'in renkli gece hayatında</arg>
<arg f="loc" n="m" suffix="">onlarca kamera önünde</arg>
<arg f="" n="1" suffix="">sevgilisini</arg>
<arg f="mnr" n="m" suffix="">itip</arg>
<rel f="">kaktı</rel>
</example>

<note/>
</roleset>

<note/>
</predicate>

<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/iğren.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="iğren">


<roleset id="iğren.01" name="Hoşlanmamak, nefret etmek">
<roles>
<role descr="iğrenen" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="experiencer"/>
</role>

<role descr="neyden iğrendiği" f="" n="1" suffix="ABL">
<vnrole vncls="" vntheta="stimulus"/>
</role>


<note/>
</roles>

<example name="tnc-NE09C2A-0324" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Gördüğüm an iğrendim adamdan.</text>



<note/>
<arg f="tmp" n="m" suffix="">Gördüğüm an</arg>
<arg f="" n="1" suffix="">adamdan</arg>
<rel f="">iğrendim</rel>
</example>


<note/>
</roleset>



<note/>
</predicate>


<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/gör.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="gör">


<roleset id="gör.01" name="Bir şeyin varlığını algılamak">
<roles>
<role descr="gören kişi" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="gördüğü şey" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="theme"/>
</role>




















<note/>
</roles>

<example name="tdk" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Merdivenin başındaki paravanın arkasında garip bir sahne gördüm.</text>




















<arg f="loc" n="m" suffix="">Merdivenin başındaki paravanın arkasında</arg>
<arg f="" n="1" suffix="">garip bir sahne</arg>
<rel f="">gördüm</rel>

<note/>
</example>




















<note/>
</roleset>
<roleset id="gör.02" name="Yapmak, etmek">
<roles>
<role descr="yapan kişi/şey" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="yaptığı iş" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="theme"/>
</role>




















<note/>
</roles>

<example name="none" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Bu makina artık iş görmez.</text>




















<arg f="" n="0" suffix="">Bu makina</arg>
<arg f="adv" n="m" suffix="">artık</arg>
<arg f="" n="1" suffix="">iş</arg>
<rel f="">görmez</rel>

<note/>
</example>




















<note/>
</roleset>
<roleset id="gör.03" name="Birşeye erişmek">
<roles>
<role descr="erişen" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="eriştiği şey" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="theme"/>
</role>




















<note/>
</roles>

<example name="tdk" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Sonunda cebi para görmüştü.</text>




















<arg f="dis" n="m" suffix="">Sonunda</arg>
<arg f="" n="0" suffix="">cebi</arg>
<rel f=""/>
<arg f="" n="1" suffix="">para</arg>

<note/>
</example>




















<note/>
</roleset>
<roleset id="gör.04" name="Çok değer vermek">
<roles>
<role descr="değer verilen şey" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="theme"/>
</role>




















<role descr="değer veren kişi/şey" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<note/>
</roles>

<example name="tdk" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Gözü yalnız parayı görüyor.</text>




















<arg f="" n="0" suffix="">Gözü</arg>
<arg f="adv" n="m" suffix="">yalnız</arg>
<arg f="" n="1" suffix="">parayı</arg>
<rel f="">görüyor</rel>

<note/>
</example>




















<note/>
</roleset>
<roleset id="gör.05" name="Yüzü bir yöne doğru olmak">
<roles>
<role descr="gören" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="theme"/>
</role>

<role descr="görülen" f="" n="4" suffix="NOM-ACC">
<vnrole vncls="" vntheta="destination"/>
</role>




















<note/>
</roles>

<example name="tdk" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Ev güneş görüyor.</text>




















<arg f="" n="1" suffix="">Ev</arg>
<arg f="" n="4" suffix="">güneş</arg>
<rel f="">görüyor</rel>

<note/>
</example>




















<note/>
</roleset>






<roleset id="gör.06" name="Bir şey hakkında bir yargıya varmak">
<roles>
<role descr="yargıya varan (gören)" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="yargıya varılan (neyi gördüğü)" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="theme"/>
</role>
<role descr="varılan yargı (nasıl gördüğü)" f="" n="2" suffix="NOM"/>















<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Bu işin sonunu iyi görmüyorum.</text>















<arg f="" n="1" suffix="">Bu işin sonunu</arg>
<arg f="" n="2" suffix="">iyi</arg>
<rel f="">görmüyorum</rel>

<note/>
</example>















<note/>
</roleset>


<roleset id="gör.07" name="Kendisine yapılmak, bir davranışla karşılaşmak">
<roles>
<role descr="davranılan kişi (gören)" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="experiencer"/>
</role>

<role descr="davranış (ne gördüğü)" f="" n="2" suffix="NOM">
<vnrole vncls="" vntheta="stimulus"/>
</role>
<role descr="davranan kişi (kimden/nereden gördüğü)" f="" n="3" suffix="ABL">
<vnrole vncls="" vntheta="source"/>
</role>













<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Yarar görmek, kötülük görmek</text>













<arg f="" n="2" suffix="">Yarar</arg>
<arg f="" n="2" suffix="">kötülük</arg>
<rel f="">görmek</rel>

<note/>
</example>













<note/>
</roleset>

<roleset id="gör.08" name="Bir işleme uğramak">
<roles>
<role descr="gören" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="patient"/>
</role>

<role descr="ne gördüğü" f="" n="2" suffix="NOM">
<vnrole vncls="" vntheta="attribute"/>
</role>












<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Teftiş görmek, tedavi görmek</text>












<arg f="" n="2" suffix="">Teftiş</arg>
<arg f="" n="2" suffix="">tedavi</arg>
<rel f="">görmek</rel>

<note/>
</example>












<note/>
</roleset>












<note/>
</predicate>






<predicate lemma="kabul_gör">


<roleset id="gör.09" name="Kabul edilmek, Onaylanmak">
<roles>
<role descr="onaylanan" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="theme"/>
</role>

<role descr="nerede kabul gördüğü" f="" n="2" suffix="LOC"/>














<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Terzaghi'nin bu izahı geniş kabul gördü.</text>














<arg f="" n="1" suffix="">Terzaghi'nin bu izahı</arg>
<arg f="ext" n="m" suffix="">geniş</arg>
<rel f="">kabul gördü</rel>

<note/>
</example>














<note/>
</roleset>














<note/>
</predicate>














<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/salla.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="salla">


<roleset id="salla.01" name="Düzenli bir biçimde ve hep aynı doğrultuda hareket ettirmek">
<roles>
<role descr="sallayan" f="" n="0" suffix="NOM"/>

<role descr="sallanan" f="" n="1" suffix="ACC"/>




<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Sen yine anahtarını çıkar, salla, eğlendir.</text>





<note/>
<arg f="" n="0" suffix="">Sen</arg>
<rel f="">salla</rel>
<arg f="tmp" n="m" suffix="">yine</arg>
</example>





<note/>
</roleset>

<roleset id="salla.02" name="Uydurmak, kafadan atmak">
<roles>
<role descr="sallayan" f="" n="0" suffix="NOM"/>

<role descr="sallanan" f="" n="1" suffix="ACC"/>



<note/>
</roles>




<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Cevabını salladım.</text>
<note/>
<arg f="" n="1" suffix="">Cevabını</arg>
<rel f="">salladım</rel>
</example>
</roleset>
<roleset id="salla.03" name="Ertelemek">
<roles>
<role descr="erteleyen" f="" n="0" suffix="NOM"/>

<role descr="ertelenen" f="" n="1" suffix="ACC"/>
<role descr="ertelenme süresi" f="" n="2" suffix="NOM"/>



<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Ev sahibinin gözünü boyarım, kalan borcu bir müddet daha sallarım diyordu</text>




<note/>
<arg f="" n="1" suffix="">kalan borcu</arg>
<arg f="" n="2" suffix="">bir müddet daha</arg>
<rel f="">sallarım</rel>
</example>



<note/>
</roleset>



<note/>
</predicate>




<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/tüket.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="tüket">


<roleset id="tüket.01" name="Kullanarak, harcayarak yok etmek, bitirmek, yoğaltmak">
<roles>
<role descr="tüketen" f="" n="0" suffix="NOM"/>

<role descr="tüketilen" f="" n="1" suffix="ACC"/>

<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Titreyen elleri baş ucundaki sürahiye gide gele içindeki suyu tüketmişti</text>


<note/>
<arg f="mnr" n="m" suffix="">Titreyen elleri baş ucundaki sürahiye gide gele</arg>
<arg f="" n="1" suffix="">içindeki suyu</arg>
<rel f="">tüketmişti</rel>
</example>

<note/>
</roleset>

<note/>
</predicate>

<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/gevşe.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="gevşe">


<roleset id="gevşe.01" name="Sertlik ve gerginliği bozulmak">
<roles>
<role descr="gevşeyen şey" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="theme"/>
</role>



<note/>
</roles>

<example name="none" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Ayakkabısının bağcıkları gevşemişti.</text>



<note/>
<arg f="" n="1" suffix="">Ayakkabısının bağcıkları</arg>
<rel f="">gevşemişti</rel>
</example>


<note/>
</roleset>


<note/>
</predicate>


<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/bastır.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="bastır">


<roleset id="bastır.01" name="öne çıkmaya çalışmak, kazanmak">
<roles>
<role descr="bastıran" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>







<note/>
</roles>







<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Haydi bastır Cimbom!</text>
<note/>
<arg f="" n="0" suffix="">Cimbom</arg>
<arg f="dis" n="m" suffix="">Haydi</arg>
</example>
</roleset>



<roleset id="bastır.02" name="gidermek">
<roles>
<role descr="gideren" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="giderilen" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="theme"/>
</role>



<note/>
</roles>




<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Açlığımı bastıracak birşeyler yemem lazım.</text>
<note/>
<arg f="" n="1" suffix="">Açlığımı</arg>
<rel f="">bastıracak</rel>
<arg f="" n="0" suffix="">birşeyler</arg>
</example>
</roleset>



<note/>
</predicate>






<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/hafifle.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="hafifle">


<roleset id="hafifle.01" name="Eski ağırlığı azalmak">
<roles>
<role descr="hafifleyen" f="" n="1" suffix="NOM"/>


<note/>
</roles>


<note/>
</roleset>

<note/>
</predicate>

<note/>
</frameset>
