=== turkishpropbank/turkishpropbank.github.io/frames/framesetTR.dtd
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>

<!ELEMENT predicate (note | roleset | infSuffixes)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>

<!ELEMENT roleset (note*, roles, ( example | note )*)>
<!ATTLIST roleset 
  id   ID #REQUIRED
  name CDATA #IMPLIED
  vncls CDATA #IMPLIED
  framnet CDATA #IMPLIED>
  
<!ELEMENT roles   (note | role)*>

<!ELEMENT role (vnrole*) >
<!ATTLIST role 
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  suffix CDATA #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #IMPLIED

  vntheta (Actor1 | Actor2| Agent| Asset| Attribute| Beneficiary| Cause|
  Destination| Experiencer| Extent| Instrument| Location| Material| Patient|
  Patient1| Patient2| Predicate| Product| Recipient| Source| Stimulus| Theme|
  Theme1| Theme2| Time| Topic) #IMPLIED>
       
<!ELEMENT infSuffix (infSuffix*)>	   
<!ATTLIST infSuffix 
  id CDATA #REQUIRED
  desc CDATA #IMPLIED>
  
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>

<!ELEMENT text (#PCDATA)>

<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">

<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  suffix CDATA #REQUIRED>
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== turkishpropbank/turkishpropbank.github.io/frames/dizginle.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="dizginle">


<roleset id="dizginle.01" name="Birinin aşırı davranışlarını önlemek">
<roles>
<role descr="dizginleyen" f="" n="0" suffix="NOM"/>

<role descr="dizginlenen" f="" n="1" suffix="ACC"/>

<note/>
</roles>


<note/>
</roleset>

<note/>
</predicate>

<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/kay.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="kay">


<roleset id="kay.01" name="Kaygan bir yüzey üzerinde sürtünerek kolayca yer değiştirmek (mecazen Durum değiştirmek, anlam değiştirmek)">
<roles>
<role descr="kayan kişi" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>




<note/>
</roles>

<example name="none" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Buzda kaymak en büyük eğlencesiydi.</text>




<note/>
<arg f="loc" n="m" suffix="">Buzda</arg>
<rel f="">kaymak</rel>
</example>



<note/>
</roleset>



<note/>
</predicate>



<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/yan.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="yan">


<roleset id="yan.01" name="Ateş durumuna geçmek, tutuşmak">
<roles>
<role descr="yanan" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="patient"/>
</role>


<note/>
</roles>


<note/>
</roleset>

<note/>
</predicate>

<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/dur.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="dur">


<roleset id="dur.01" name="Hareketsiz durumda olmak, kalmak">
<roles>
<role descr="duran kişi/şey" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>



<role descr="nerede durduğu" f="" n="2" suffix="LOC">
<vnrole vncls="" vntheta="location"/>
</role>
<note/>
</roles>

<example name="tdk" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Motorlu su taşıtlarından biri de kanal rıhtımının tam bizim önümüze düşen bir noktasında demir atmış duruyordu.</text>



<note/>
<arg f="" n="0" suffix="">Motorlu su taşıtlarından biri (de)</arg>
<arg f="" n="2" suffix="">kanal rıhtımının tam bizim önümüze düşen bir noktasında</arg>
<arg f="mnr" n="m" suffix="">demir atmış</arg>
<rel f="">duruyordu</rel>
</example>
<example name="tdk2" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Bileğimdeki saat durmuş.</text>



<note/>
<arg f="" n="0" suffix="">Bileğimdeki saat</arg>
<rel f="">durmuş</rel>
</example>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Yağmur durdu.</text>



<note/>
<arg f="" n="0" suffix="">Yağmur</arg>
<rel f="">durdu</rel>
</example>
<example name="tdk5" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Türklerin yüzlerce yıl önceki kitabeleri hâlâ duruyor.</text>



<note/>
<arg f="" n="0" suffix="">Türklerin yüzlerce yıl önceki kitabeleri</arg>
<arg f="adv" n="m" suffix="">hâlâ</arg>
<rel f="">duruyor</rel>
</example>
<example name="tdk" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Yazlık eviniz hâlâ duruyor mu?</text>



<note/>
<arg f="" n="0" suffix="">Yazlık eviniz</arg>
<arg f="adv" n="m" suffix="">hâlâ</arg>
<rel f="">duruyor mu</rel>
</example>
<example name="tdk11" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Aspirin getirmeyeceğini adı gibi biliyordu çünkü çekmecesinde dokunulmamış bir kutu duruyordu.</text>



<note/>
<arg f="dis" n="m" suffix="">çünkü</arg>
<arg f="" n="2" suffix="">çekmecesinde</arg>
<arg f="" n="0" suffix="">dokunulmamış bir kutu</arg>
<rel f="">duruyordu</rel>
</example>


<note/>
</roleset>


<note/>
</predicate>


<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/güreş.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="güreş">


<roleset id="güreş.01" name="İki kişi türlü oyunlarla birbirinin sırtını yere getirmeye çalışmak">
<roles>
<role descr="güreşen" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="actor1"/>
</role>

<role descr="kiminle güreştiği" f="" n="1" suffix="WITH">
<vnrole vncls="" vntheta="actor2"/>
</role>



<note/>
</roles>

<example name="tnc-FD36C2A-0564" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Ama çocuk fırsatını buldu mu, koca öküzün sırtına bile biner, boğanın üstünden atlar, köpeğiyle güreşir.</text>




<note/>
<arg f="dis" n="m" suffix="">Ama</arg>
<arg f="" n="0" suffix="">çocuk</arg>
<arg f="tmp" n="m" suffix="">fırsatını buldu mu</arg>
<arg f="" n="1" suffix="">köpeğiyle</arg>
<rel f="">güreşir</rel>
</example>



<note>işteş</note>
</roleset>




<note/>
</predicate>



<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/boşan.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="boşan">


<roleset id="boşan.01" name="Ayrılmak">
<roles>
<role descr="boşanan" f="" n="0" suffix="NOM"/>

<role descr="kimden boşandığı" f="" n="3" suffix="ABL"/>
<note/>
</roles>

<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Sonunda ondan boşandım.</text>
<note/>
<arg f="adv" n="m" suffix="">Sonunda</arg>
<arg f="" n="3" suffix="">ondan</arg>
</example>
</roleset>
<note/>
</predicate>
<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/kıskan.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="kıskan">


<roleset id="kıskan.01" name="bir başkasının ortaklığına, üstün durumda görünmesine dayanamamak">
<roles>
<role descr="kıskanan kişi" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="experiencer"/>
</role>

<role descr="kıskanılan kişi" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="stimulus"/>
</role>
<role descr="neyden/kimden kıskandığı" f="" n="2" suffix="ABL">
<vnrole vncls="" vntheta="theme2"/>
</role>



<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Mühür gözlüm seni elden / Sakınırım, kıskanırım.</text>




<note/>
<arg f="" n="1" suffix="">seni</arg>
<arg f="" n="2" suffix="">elden</arg>
<rel f="">kıskanırım</rel>
</example>



<note/>
</roleset>



<note/>
</predicate>



<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/kıpırda.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="kıpırda">


<roleset id="kıpırda.01" name="Kımıldamak, sürekli ve hafifçe oynamak">
<roles>
<role descr="kıpırdayan" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="theme"/>
</role>



<note/>
</roles>



<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Hasta kıpırdadı.</text>
<note/>
<arg f="" n="1" suffix="">Hasta</arg>
<rel f="">kıpırdadı</rel>
</example>
</roleset>


<note/>
</predicate>


<note/>
</frameset>
