=== turkishpropbank/turkishpropbank.github.io/frames/framesetTR.dtd
<!ELEMENT frameset (note | predicate)*>
<!ELEMENT note (#PCDATA)>

<!ELEMENT predicate (note | roleset | infSuffixes)*>
<!ATTLIST predicate lemma CDATA #REQUIRED>

<!ELEMENT roleset (note*, roles, ( example | note )*)>
<!ATTLIST roleset 
  id   ID #REQUIRED
  name CDATA #IMPLIED
  vncls CDATA #IMPLIED
  framnet CDATA #IMPLIED>
  
<!ELEMENT roles   (note | role)*>

<!ELEMENT role (vnrole*) >
<!ATTLIST role 
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  suffix CDATA #REQUIRED
  descr CDATA #REQUIRED>

<!ELEMENT vnrole EMPTY>
<!ATTLIST vnrole
  vncls CDATA #IMPLIED

  vntheta (Actor1 | Actor2| Agent| Asset| Attribute| Beneficiary| Cause|
  Destination| Experiencer| Extent| Instrument| Location| Material| Patient|
  Patient1| Patient2| Predicate| Product| Recipient| Source| Stimulus| Theme|
  Theme1| Theme2| Time| Topic) #IMPLIED>
       
<!ELEMENT infSuffix (infSuffix*)>	   
<!ATTLIST infSuffix 
  id CDATA #REQUIRED
  desc CDATA #IMPLIED>
  
<!ELEMENT example (inflection?, note?, text, (arg | rel | note)*)>
<!ATTLIST example
  name CDATA #IMPLIED
  type CDATA #IMPLIED
  src  CDATA #IMPLIED>

<!ELEMENT text (#PCDATA)>

<!ELEMENT inflection EMPTY>
<!ATTLIST inflection
  person (third | other | ns) "ns"
  tense  (present | past | future | ns) "ns"
  aspect (perfect | progressive | both | ns) "ns"
  voice  (active | passive | ns) "ns"
  form   (infinitive | gerund | participle | full | ns) "ns">

<!ELEMENT arg (#PCDATA)>
<!ATTLIST arg
  n CDATA #REQUIRED
  f CDATA #IMPLIED
  suffix CDATA #REQUIRED>
<!ELEMENT rel (#PCDATA)>
<!ATTLIST rel
  f CDATA #IMPLIED>

=== turkishpropbank/turkishpropbank.github.io/frames/tutul.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="tutul">


<roleset id="tutul.01" name="aÅŸÄ±k olmak">
<roles>
<role descr="tutulan" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="experiencer"/>
</role>

<role descr="neye tutulduÄŸu" f="" n="1" suffix="DAT">
<vnrole vncls="" vntheta="stimulus"/>
</role>
<note/>
</roles>

<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Ben sana tutuldum.</text>
<note/>
<arg f="" n="0" suffix="">Ben</arg>
<arg f="" n="1" suffix="">sana</arg>
<rel f="">tutuldum</rel>
</example>
</roleset>
<note/>
</predicate>
<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/sürt.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="sürt">


<roleset id="sürt.01" name="Bir şeyi bastırarak diğer bir şeyin üzerinden geçirmek">
<roles>
<role descr="sürten" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="sürtülen şey" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="theme"/>
</role>
<role descr="nereye sürtüldüğü" f="" n="2" suffix="DAT">
<vnrole vncls="" vntheta="destination"/>
</role>

<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Cemal ellerini hızlı hızlı birbirine sürttü.</text>


<note/>
<arg f="" n="0" suffix="">Cemal</arg>
<arg f="" n="1" suffix="">ellerini</arg>
<arg f="mnr" n="m" suffix="">hızlı hızlı</arg>
<arg f="" n="2" suffix="">birbirine</arg>
<rel f="">sürttü</rel>
</example>

<note/>
</roleset>

<note/>
</predicate>

<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/fışkır.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="fışkır">


<roleset id="fışkır.01" name="Yukarıya doğru birdenbire ve hızla çıkmak">
<roles>
<role descr="fışkıran şey" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="theme"/>
</role>

<role descr="nereden fışkırdığı" f="" n="2" suffix="ABL">
<vnrole vncls="" vntheta="source"/>
</role>




<note/>
</roles>

<example name="tdk" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Hemen hemen memleketimizin dört bucağından su fışkırmasıdır.</text>





<arg f="" n="2" suffix="">Hemen hemen memleketimizin dört bucağından</arg>
<arg f="" n="1" suffix="">su</arg>
<rel f="">fışkırmasıdır</rel>
<note/>
</example>





<note/>
</roleset>



<roleset id="fışkır.02" name="Bol bol olmak">
<roles>
<role descr="bol olan şey" f="" n="1" suffix="NOM"/>

<role descr="nerede bol olduğu" f="" n="2" suffix="ABL"/>

<note/>
</roles>

<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Kaldırım taşları arasından fışkırmış otların bütün sokağı bürüyeceği muhakkak</text>


<arg f="" n="2" suffix="">Kaldırım taşları arasından</arg>
<arg f="" n="1" suffix="">otların</arg>
<rel f="">fışkırmış</rel>
<note/>
</example>

<note/>
</roleset>

<note/>
</predicate>




<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/ılı.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="ılı">


<roleset id="ılı.01" name="Ilınmak">
<roles>
<role descr="ılık duruma gelen kişi/şey" f="" n="1" suffix="NOM">
<vnrole vncls="" vntheta="patient"/>
</role>



<note/>
</roles>

<example name="tnc-KA16B4A-0121" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Kaynar su birazcık ılıdı.</text>



<note/>
<arg f="" n="1" suffix="">Kaynar su</arg>
<arg f="ext" n="m" suffix="">birazcık</arg>
<rel f="">ılıdı</rel>
</example>


<note/>
</roleset>


<note/>
</predicate>


<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/yuvarla.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="yuvarla">


<roleset id="yuvarla.01" name="İlerletmek, götürmek">
<roles>
<role descr="yuvarlayan" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="yuvarlanan" f="" n="1" suffix="ACC">
<vnrole vncls="" vntheta="theme"/>
</role>
<role descr="nereye yuvarlandığı" f="" n="2" suffix="DAT">
<vnrole vncls="" vntheta="destination"/>
</role>
<note/>
</roles>

<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>3,6'yı 4'e yuvarlaman yeterli.</text>
<note/>
<arg f="" n="1" suffix="">3,6'yı</arg>
<arg f="" n="2" suffix="">4'e</arg>
<rel f="">yuvarlaman</rel>
</example>
</roleset>
<note/>
</predicate>
<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/kırıt.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="kırıt">


<roleset id="kırıt.01" name="cilveli davranışlarda bulunmak">
<roles>
<role descr="kırıtan" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>



<note/>
</roles>



<note/>
</roleset>


<note/>
</predicate>


<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/tiksin.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="tiksin">


<roleset id="tiksin.01" name="Aşağılık bulmak">
<roles>
<role descr="tiksinen" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="experiencer"/>
</role>

<role descr="neyden tiksindiği" f="" n="3" suffix="ABL">
<vnrole vncls="" vntheta="stimulus"/>
</role>
<note/>
</roles>

<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Kıllarından tiksiniyorum.</text>
<note/>
<arg f="" n="3" suffix="">Kıllarından</arg>
<rel f="">tiksiniyorum</rel>
</example>
</roleset>
<note/>
</predicate>
<note/>
</frameset>

=== turkishpropbank/turkishpropbank.github.io/frames/barın.xml
<!DOCTYPE frameset SYSTEM "framesetTR.dtd">
<frameset>

<predicate lemma="barın">


<roleset id="barın.01" name="Oturmak, yaşamak, tutunmak">
<roles>
<role descr="barınan" f="" n="0" suffix="NOM">
<vnrole vncls="" vntheta="agent"/>
</role>

<role descr="barınılan yer" f="" n="2" suffix="LOC">
<vnrole vncls="" vntheta="location"/>
</role>
<note/>
</roles>

<note/>
<example name="" src="" type="">
<inflection aspect="ns" form="ns" person="ns" tense="ns" voice="ns"/>
<text>Seni burada barındırmazlar.</text>
<note/>
<arg f="" n="2" suffix="">burada</arg>
<arg f="" n="0" suffix="">Seni</arg>
</example>
</roleset>
<note/>
</predicate>
<note/>
</frameset>
